# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366460f977efb9283f9c0970058418efb1327c61c295d17589e241a57f513f44f049f92b779bd98cca22c30c9aac4b70dd870c145667b770b824e27214f74978

test:
  secret_key_base: 373722e22e08e27214085e3261ba08b9c4e6bca0dbd10728bd59e566c58b8a7c48caf5f29701212c0e6e8f58dbd5003cabda7aa8ed65bdd1c0064207a7c35d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
